cargo-features = ["codegen-backend"]

[package]
name = "gravity_basins"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = { version = "23.0.1", default-features = false, features = ["wgsl"] }
