cargo-features = ["codegen-backend"]

[package]
name = "gravity_basins"
version = "0.1.0"
edition = "2024"

[dependencies]
encase = "0.10.0"
wgpu = { version = "23.0.1", default-features = false, features = ["wgsl"] }
winit = { version = "0.30.5", default-features = false, features = [
  "wayland",
  "rwh_06",
] }

[build-dependencies]
wgsl_to_wgpu = "0.12.0"
