
[build]
target = "spirv-unknown-vulkan1.2"
rustflags = [
    "-Zcodegen-backend=/home/julius/Code/rust/compute-shaders/rust-gpu/target/release/librustc_codegen_spirv.so",
    "-Zbinary-dep-depinfo",
    "-Csymbol-mangling-version=v0",
    "-Zcrate-attr=feature(register_tool)",
    "-Zcrate-attr=register_tool(rust_gpu)"
]

[unstable]
build-std=["core"]
build-std-features=["compiler-builtins-mem"]
